# Generated by Django 4.0.6 on 2022-07-26 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='CSVRead',
            fields=[
                ('statementupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Statement.statementupload')),
            ],
            bases=('Statement.statementupload',),
        ),
    ]
