# Generated by Django 4.0.6 on 2022-07-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('desc', models.CharField(max_length=100, verbose_name='desc')),
                ('category', models.CharField(max_length=100, verbose_name='desc')),
                ('bank', models.CharField(max_length=100, verbose_name='bank')),
            ],
        ),
        migrations.DeleteModel(
            name='CSVRead',
        ),
    ]
